flowchart LR
  Client[Client Browser]
  Web[Nginx]
  PHP[PHP-FPM / Laravel]
  MySQL[(MySQL 8.0)]
  Redis[(Redis 7)]
  Rabbit[(RabbitMQ 3.12)]
  Storage[(Local FS)]
  Scanner[Scanner Service]

  Client --> Web --> PHP
  PHP --> MySQL
  PHP --> Redis
  PHP --> Rabbit
  PHP --> Storage
  PHP --> Scanner
